# Generated by Django 3.2.4 on 2021-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='assets/images/product_03.jpg', upload_to='img/course_list')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
