# Generated by Django 3.2.4 on 2021-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=50, upload_to='img/course_list')),
                ('price', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
